<a href="https://colab.research.google.com/github/bivar/numerico/blob/master/numerico_mod_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# TO-DO 
1. Newton p sistemas não lineares
2. Interpolação
3. Pol de Lagrange  
4. Pol de Newton



In [ ]:
!python -m pip install scipy
!pip install matrix

  Created wheel for configparser2: filename=configparser2-4.0.0-cp36-none-any.whl size=20389 sha256=7d02ea816367b104134b46c0abe359a5a7e14efb4f12bf6e602a7fe3847f9749
  Stored in directory: /root/.cache/pip/wheels/ae/9a/da/aded1f1ec0cec163277c62e1ffb6841fb8c88c8356cd6280d9
Successfully built configparser2


# Métodos Numéricos - Módulo 2

## Imports

[LU](https://sites.google.com/site/cnumer3q16/atividade3#:~:text=Um%20c%C3%B3digo%20em%20Python%20para,de%20colunas%20em%20uma%20linha.&text=O%20m%C3%A9todo%20de%20Decomposi%C3%A7%C3%A3o%20%C3%A9%20baseado%20na%20resolu%C3%A7%C3%A3o%20de%20sistemas%20triangulares)

[Cholesky](https://www.quantstart.com/articles/Cholesky-Decomposition-in-Python-and-NumPy/)

[Jacobi](https://www.quantstart.com/articles/Jacobi-Method-in-Python-and-NumPy/)

[Jacobi e Gauss Seidel](https://www.ufrgs.br/reamat/CalculoNumerico/livro-py/sdsl-metodos_iterativos_para_sistemas_lineares.html)

In [ ]:
import numpy as np
import sympy as sp
import scipy.linalg
import matplotlib as plt
from __future__ import division
from prettytable import PrettyTable
from numpy.linalg import norm
from numpy import array, zeros, diag, diagflat, dot
from copy import deepcopy
from pprint import pprint

## Fatoração LU 


In [ ]:
def LU(A, b):
    #DOOLITTLE METHOD - lower matrix has its diagonal all as 1s
    permut, lower, upper = scipy.linalg.lu(A)
    # Multiplication factors
    # ------ LEMBRETE ----- #
    # Adicionar os demais   #
    # valores de m, a       #
    # depender do tam da    #
    # matriz A              #
    # --------------------- #
    '''
    m21 = lower[1,0]
    m31 = lower[2,0]
    m32 = lower[2,1]    
    m_values = PrettyTable()
    m_values.field_names = ["m_21", "m_31", "m_32"]
    m_values.add_row([m21, m31, m32])
    print(m_values, "\n")    
    '''
    #Regra 1: Ly = b
    y = scipy.linalg.solve(lower, b)
    #print("Y = ", y,"\n")
    #Regra 2: Ux = y
    x = scipy.linalg.solve(upper, y)
    #print("X = ", x, "\n")
    return lower, upper, x
    

# ----- Questão Teste ----- #

a = np.array([[8.0,4.0,-1.0], 
             [-2.0,5.0,1.0], 
             [2.0,-1.0,6.0]])

b1 = np.array([11.0, 4.0, 7.0])




# --- Q1 PROVA ---- #

A = np.array([[0.7071,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
      [0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
      [0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
      [-0.7071,0.0,0.0,1.0,0.6585,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
      [0.7071,0.0,1.0,0.0,0.7526,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
      [0.0,0.0,0.0,-1.0,0.0,0.0,1.0,0.6585,0.0,0.0,0.0,0.0,0.0],
      [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7526,1.0,0.0,0.0,0.0,0.0],
      [0.0,0.0,0.0,0.0,-0.6585,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],
      [0.0,0.0,0.0,0.0,0.7526,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0],
      [0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.7071,0.0,0.0],
      [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7071,1.0,0.0],
      [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7526,0.0,0.0,0.0,1.0,0.0],
      [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7071,0.0,1.0]])

b = np.array([0.0,0.0,2000.0,0.0,-1000.0,0.0,-500.0,0.0,4000.0,0.0,-500.0,2000.0,0.0])
print("AQUI", A.shape, b.shape)


lower, upper, x = LU(A,b)

print("# ------ VETOR B ------ #\n")
print(b)

F = x.tolist()
print("\n# ------ VETOR F ------ #\n")
for f in F:
  print(f)

fmax = abs(max(F, key=abs))
print("\n# ------ || F ||∞ = ", fmax, " ------ #")

AQUI (13, 13) (13,)
# ------ VETOR B ------ #

[    0.     0.  2000.     0. -1000.     0.  -500.     0.  4000.     0.
  -500.  2000.     0.]

# ------ VETOR F ------ #

-6882.56866701081
4866.664304443343
2000.0
-6499.933563646029
2480.287409571277
4866.664304443343
-4633.335695556659
-2834.6209082602422
2133.3356955566583
5999.933563646028
-6552.589019313617
4133.335695556659
4633.335695556659

# ------ || F ||∞ =  6882.56866701081  ------ #


In [ ]:

A = [[0.7071, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,0.0],
    [0.0, -1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2000.0],
    [-0.7071, 0.0, 0.0, 1.0, 0.6585, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ,0.0, 0.0, 0.0],
    [0.7071, 0.0, 1.0, 0.0, 0.7526, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1000],
    [0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 1.0, 0.6585, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7526, 1.0, 0.0, 0.0, 0.0, 0.0, -500.0],
    [0.0, 0.0, 0.0, 0.0, -0.6585, -1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.7526, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 4000.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.7071, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7071, 1.0, 0.0, -500.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7526, 0.0, 0.0, 0.0, 1.0, 0.0, 2000.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7071, 0.0, 1.0, 0.0]]

def gaussian_elimination_with_pivot(A):   
  n = len(A)
  for i in range(n):
    # Determinação do pivo atual
    # Pivo sendo maior valor da linha
    pivot(A, n, i)
    for j in range(i+1, n):
      A[j] = [A[j][k] - A[i][k]* float (A[j][i])/float(A[i][i]) for k in range(n+1)]
  #Substituição de trás pra frente 
  x = [0] * n
  for i in range(n-1, -1, -1):
    s = sum(A[i][j] * x[j] for j in range(i, n))
    x[i] = (A[i][n] - s) / A[i][i]
  return x


# Função auxiliar, pega o maior valor da linha
def pivot(A, n, i):
  max_row = max(range(i, n), key=lambda r: abs(A[r][i]))
  A[i], A[max_row] = A[max_row], A[i]


F = gaussian_elimination_with_pivot(A)
print("\n# ------ VETOR F ------ #\n")
for f in F:
  print(f)

fmax = abs(max(F, key=abs))
print("\n# ------ || F ||∞ = ", fmax, " ------ #")


# ------ VETOR F ------ #

-7236.125448229872
5116.664304443342
2000.0
-6968.67525910178
2812.4691794357454
5116.664304443342
-4883.335695556659
-3166.8026781247117
1883.3356955566583
6968.675259101781
-6906.145800532681
4383.335695556659
4883.335695556659

# ------ || F ||∞ =  7236.125448229872  ------ #


## Cholesky


In [ ]:
def sylvester(A):
  is_pos_def = np.all(np.linalg.eigvals(A) > 0)
  if(is_pos_def):
    print("Satisfaz o critério de Sylvester\n")
  else:
    print("Não satisfaz o critério de Sylvester\n")

def cholesky(A, b):  
  G = scipy.linalg.cholesky(A, lower=True)
  G_t = scipy.linalg.cholesky(A, lower=False)
  # values of G
  # ------ LEMBRETE ----- #
  # Adicionar os demais   #
  # valores de G, a       #
  # depender do tam da    #
  # matriz A              #
  # --------------------- #
  g_11 = G[0,0]
  g_21 = G[1,0]
  g_22 = G[1,1]
  g_31 = G[2,0]
  g_32 = G[2,1]
  g_33 = G[2,2]
  g_values = PrettyTable()
  g_values.field_names = ["g_11", "g_21", "g_22", "g_31", "g_32", "g_33"]
  g_values.add_row([g_11, g_21, g_22, g_31, g_32, g_33])
  print(g_values, "\n")
  #Regra 1: Gy = b
  y = scipy.linalg.solve(G, b)
  print("Y = [", y, "]", "\n")
  #Regra 2: G_tx = y
  x = scipy.linalg.solve_triangular(G_t, y)
  print("X = [", x, "]", "\n")
  return G, G_t

# ----- TESTE ----#
'''
A = np.array([[2.0,-1.0,0.0],
              [-1.0,2.0,-1.0],
              [0.0,-1.0,2.0]])

B = A = np.array([[8.0,20.0,15.0],
              [20.0,80.0,50.0],
              [15.0,50.0,60.0]])

'''
# --- Q1 PROVA ---- #
A = np.array([[0.7071,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
              [0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
              [0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
              [-0.7071,0.0,0.0,1.0,0.6585,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
              [0.7071,0.0,1.0,0.0,0.7526,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
              [0.0,0.0,0.0,-1.0,0.0,0.0,1.0,0.6585,0.0,0.0,0.0,0.0,0.0],
              [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7526,1.0,0.0,0.0,0.0,0.0],
              [0.0,0.0,0.0,0.0,-0.6585,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],
              [0.0,0.0,0.0,0.0,0.7526,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0],
              [0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.7071,0.0,0.0],
              [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7071,1.0,0.0],
              [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7526,0.0,0.0,0.0,1.0,0.0],
              [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7071,0.0,1.0]])

b = np.array([0.0,0.0,2000.0,0.0,-1000.0,0.0,-500.0,0.0,4000.0,0.0,-500.0,-2000.0,0.0])
x0 = np.array([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0])
N = 150
cp = 10**-3


sylvester(A)
#G, G_t = cholesky(A, b)
#print("Matriz G: \n", G, "\n")
#print("Matriz G_t:\n", G_t)

Não satisfaz o critério de Sylvester



## Jacobi

In [ ]:
# ------ Resumo ------- #
# A - Matriz A          #
# b - vetor do sistema  #
# x0 - chutes iniciais  #
# cp - crit. de parada  #
# N - num max de iter.  #
# --------------------- #

# Lembrando que: isola-se a iesima 
# variavel na correspondente iesima eq do sistema

# Processo: calculo -> armazeno -> uso

def jacobi(A,b,x0,N, cp):  
  # Chutes possíveis  
  x = x0
  # MATRIZ DIAGONAL
  DIAG = np.diag(A)
  print("Matriz diagonal \n", DIAG)
  # MATRIZ COMPLEMENTAR
  COMP = A - np.diagflat(DIAG)
  print("Matriz complementar \n", COMP)

  for i in range(N):
    # ----- FUNC. ITERAÇÃO ----- #
    # xi(k+1) = 1/aii (bi - phi) #
    print("Solução atual", x)
    x_new = (b - np.dot(COMP,x))/ DIAG
    # Critério de parada
    # Erro absoluto < criterio de parada
    if(np.allclose(x,x_new,atol=cp,rtol=0.)):
      print("Atingiu o criterio de parada na iteração", i+1)
      print("O erro é de", (x_new - x))
      break
    else:
        x = x_new

  return x

# ---- QUESTAO DE TESTE ----#
'''
A = np.array([[2.0,1.0],[5.0,7.0]])
b = np.array([11.0,13.0])
x0 = np.asarray([1.0,1.0])
N = 151
cp = 10**-2
'''

# ---- QUESTAO DE TESTE ---- #
'''A = np.array([[10.0,2.0,1.0],[1.0,5.0,1.0],[2.0,3.0,10.0]])
b = np.array([7.0,-8.0,6.0])
x0 = np.array([1.0,1.0,1.0]) 
N = 151
cp = 10**-3
'''
# ---- QUESTAO 1(a) LISTA 4 ---- #
'''
A = np.array([[2.0,-1.0],[1.0,2.0]])
b = np.array([1.0,3.0])
x0 = np.asarray([0.0,0.0])
N = 150
cp = 10**-3
'''

# ---- QUESTAO 1(b) LISTA 4 ---- #

A = np.array([[1.0,-0.25,-0.25,0.0],
              [-0.25,1.0,0.0,-0.25],
              [-0.25,0.0,1.0,-0.25],
              [0.0,-0.25,0.0,1.0]])
b = np.array([0.0,0.0,0.25,0.25])
x0 = np.asarray([0.0,0.0,0.0,0.0])
N = 150
cp = 10**-3




#print(A.shape)
#print(b)
x= jacobi(A,b,x0,N, cp)
print("Solução:", x)


Matriz diagonal 
 [1. 1. 1. 1.]
Matriz complementar 
 [[ 0.   -0.25 -0.25  0.  ]
 [-0.25  0.    0.   -0.25]
 [-0.25  0.    0.   -0.25]
 [ 0.   -0.25  0.    0.  ]]
Solução atual [0. 0. 0. 0.]
Solução atual [0.   0.   0.25 0.25]
Solução atual [0.0625 0.0625 0.3125 0.25  ]
Solução atual [0.09375  0.078125 0.328125 0.265625]
Solução atual [0.1015625  0.08984375 0.33984375 0.26953125]
Solução atual [0.10742188 0.09277344 0.34277344 0.27246094]
Solução atual [0.10888672 0.0949707  0.3449707  0.27319336]
Solução atual [0.10998535 0.09552002 0.34552002 0.27374268]
Atingiu o criterio de parada na iteração 8
O erro é de [0.00027466 0.00041199 0.00041199 0.00013733]
Solução: [0.10998535 0.09552002 0.34552002 0.27374268]


## Gauss-Seidel

In [ ]:
# TA FALTANDO POR O CRITÉRIO DE PARADA

def gseidel(A,b,cp,N):
  x = np.zeros_like(b)
  x_new = x
  n = x.shape[0]
  for k in range(N):   
    for i in range(n):
      sum = 0
      for j in range(n):
        if(j==i):
          continue
        # ITERAÇÃO DE GAUSS-SEIDEL
        sum += A[i,j]*x[j]
        x[i] = (b[i] - sum)/A[i,i]  
    print('Solução da iteração', k,':', x)
  return x

# ---- QUESTAO 3 LISTA 4 ---- #
'''
A = np.array([[10.0,2.0,-1.0],
              [-3.0,-6.0,2.0],
              [1.0,1.0,5.0]])
b = np.array([27.0,-61.5,-21.5])
N = 15
cp = 0.05 
'''

# ---- QUESTAO 5 LISTA 5 ---- #
'''A = np.array([[4.0,3.0,2.0],
              [1.0,3.0,1.0],
              [2.0,1.0,3.0]])
b = np.array([960.0,510.0,610.0])
N = 25
cp = 0.05'''



x = gseidel(A,b,cp, N)
print("Sol:", x)

NameError: ignored

## Questão 2 prova


In [ ]:
x = 0.000000231*(222**2) - 0.00068074*222 +1.052589440
print(x)
print('Alternativa D')

0.912849764
Alternativa D
